name: lume-distgen-impact-cu-inj-dev
channels:
  - conda-forge
dependencies:
  - click
  - pydantic # until lume-services registered with conda
  - docker-py>=5.0  # until lume-services registered with conda
  - graphviz  # until lume-services registered with conda
  - python-graphviz  # until lume-services registered with conda
  - prefect[viz]<2.0 # until lume-services registered with conda
  - numpy
  - scikit-image
  - lume-impact
  - distgen
  - pandas
  - pip 
  - lume-model>=1.4.6
  - pip: 
    - git+https://github.com/slaclab/lume-services.git@main

  # dev
  - pre-commit
  - pytest
  - pytest-cov
  - jupyterlab
