name: Build Container Image

on:
  push:
    tags:
      - "*"

jobs:
  push_to_registry:
    name: Build and Push to SCR
    runs-on: ubuntu-latest
    env:
      REPO: lume-distgen-impact-cu-inj
      
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: scr.svc.stanford.edu
          username: ${{ secrets.STANFORD_USERNAME }}
          password: ${{ secrets.SCR_PAT }}

      - name: Build image
        run: |
          docker build -t ${{ env.REPO }} . --build-arg VERSION=${{ github.ref_name }} 
      
      - name: Tag images
        run: |
          docker tag ${{ env.REPO }} scr.svc.stanford.edu/${{ secrets.STANFORD_USERNAME }}/${{ env.REPO }}:latest
          docker tag ${{ env.REPO }} scr.svc.stanford.edu/${{ secrets.STANFORD_USERNAME }}/${{ env.REPO }}:${{ github.ref_name }}

      - name: Push image
        run: |
          docker image push scr.svc.stanford.edu/${{ secrets.STANFORD_USERNAME }}/${{ env.REPO }}:latest
          docker image push scr.svc.stanford.edu/${{ secrets.STANFORD_USERNAME }}/${{ env.REPO }}:${{ github.ref_name }}

